name: rikulo_todoMVC
version: 0.5.0
description: Rikulo's implementation of todoMVC.
authors:
- Simon Pai <simonpai@rikulo.org>
homepage: http://rikulo.org
dependencies:
  rikulo: any
  rikulo_uxl: '>=0.5.1'
